name: Deploy to Firebase Hosting on Push

'on': workflow_dispatch

jobs:

    deploy:

     runs-on: ubuntu-latest

     steps:

      - uses: actions/checkout@v2

      - name: Install Packages

        run: npm install   

      - name: Build App

        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0

        with:

          repoToken: '${{ secrets.GITHUB_TOKEN }}'

          firebaseServiceAccount: '${{ secrets.GIT_PRACTICE_HELLO }}'

          projectName: gitpractice1

          channelId: live
